# Generated by Django 3.1.12 on 2025-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
