# Generated by Django 3.1.12 on 2025-07-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_copy_lugar_to_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='Eventos',
        ),
    ]
