# Generated by Django 3.1.12 on 2025-07-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20250710_1200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='eventos',
        ),
    ]
