"""
Django settings for cobien project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.utils.translation import gettext_lazy as _



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-yt@44*)wj6ef$95f3e5_rt$+qkx13v$gl1kh8rdcsr%r)=22!(')


# SECURITY WARNING: don't run with debug turned on in production!
# If u want to work on local comment the next line and comment the one afters and descoment de second DEBUG and the allowed hosts for local development
DEBUG = os.getenv('DEBUG', 'False') == 'True'


ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS', '.onrender.com'
).split(',') 

DEBUG = True

# allowed host in local development
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    # Project apps
    'apps.eventos',
    'apps.asociacion',
    'apps.emociones',
    'apps.accounts',
    'apps.pizarra',

    # Django core whithout user dependency
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # Django que that use auth
    'django.contrib.auth',
    'django.contrib.admin',

    # static files
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',

]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',



]

ROOT_URLCONF = 'cobien.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cobien.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': os.getenv('DB_NAME', 'LabasAppDB'),
        'CLIENT': {
            'host': os.getenv('MONGO_URI', 'mongodb+srv://usuarioCoBien:passwordCoBien@clustercobienevents.j8ev5.mongodb.net/?retryWrites=true&w=majority&appName=ClusterCoBienEvents'),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL          = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Enable internationalization
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', _('Español')),
    ('fr', _('Français')),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Location of translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Ensure that Django saves the language in the session
LANGUAGE_COOKIE_NAME = 'django_language'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_ENGINE = 'django.contrib.sessions.backends.db' # save session data in the database

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'apps/eventos/static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Twilio credentials
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', 'AC028c91441b201dcb8b2ea31ac92ea82a')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', "5b4fc9557b92cfa3f2a0ddfdc9d120e8")
TWILIO_API_KEY = os.getenv('TWILIO_API_KEY', 'SK75b6011bed4f95a3950605b167324007')
TWILIO_API_SECRET = os.getenv('TWILIO_API_SECRET', 'HX2mXk6GdHsIuHVgxpnAJPAzX6U70QQX')
TWILIO_CONVERSATION_SERVICE_SID = os.getenv('TWILIO_CONVERSATION_SERVICE_SID', "ISc2e4d6905f1945cd9a85367ee4b6f1d3")

if not DEBUG:  # Only in production
    CSRF_TRUSTED_ORIGINS = [os.getenv('RENDER_EXTERNAL_URL', 'https://proyecto-cobien.onrender.com')]

# === Notifications ===
NOTIFY_API_KEY    = os.getenv("NOTIFY_API_KEY", "")  
NOTIFY_TTL_HOURS  = int(os.getenv("NOTIFY_TTL_HOURS", "24"))

# MQTT configuration
MQTT_BROKER_URL  = os.getenv('MQTT_BROKER_URL', 'broker.hivemq.com')
MQTT_BROKER_PORT = int(os.getenv('MQTT_BROKER_PORT', 1883))
MQTT_USERNAME    = os.getenv('MQTT_USERNAME', '')
MQTT_PASSWORD    = os.getenv('MQTT_PASSWORD', '')
MQTT_TOPIC_GENERAL   = os.getenv("MQTT_TOPIC_GENERAL",  "tarjeta")
MQTT_TOPIC_VIDEOCALL = os.getenv("MQTT_TOPIC_VIDEOCALL", "videollamada")

"""# Configuración del backend de correo electrónico
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "CoBien <no-reply@cobien.local>"""

# backend configuration for production with Resend

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.resend.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "resend"  # literal
EMAIL_HOST_PASSWORD = os.getenv("RESEND_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "CoBien <no-reply@portal.co-bien.eu>")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.EmailOrUsernameModelBackend",  # our backend
]

# Links expire time for password reset tokens (in seconds)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True